-- =========================================================
-- Worklogs & Completed Tasks Activity Tracking Migration
-- =========================================================

-- 1. Create worklogs table
CREATE TABLE IF NOT EXISTS public.worklogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE SET NULL,
  user_uid TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT DEFAULT 'General',
  hours_spent NUMERIC(5,2) DEFAULT 1.0,
  log_source TEXT DEFAULT 'Manual', -- 'Manual' or 'Task Completion'
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.worklogs ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
DROP POLICY IF EXISTS "Allow all on worklogs" ON public.worklogs;
CREATE POLICY "Allow all on worklogs" ON public.worklogs
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- 4. Grant Permissions to anon, authenticated, and service_role
GRANT ALL ON TABLE public.worklogs TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 5. Optional: Register '/worklogs' route in public.routes table
INSERT INTO public.routes (name, path, icon, sort_order)
VALUES ('Worklogs', '/worklogs', 'file-text', 5)
ON CONFLICT (path) DO NOTHING;
