import { useState } from 'react'
import {
  FileText,
  AlertTriangle,
  CheckCircle2,
  Plus,
  Search,
  X,
  RefreshCw,
  Calendar,
  Clock,
  Edit3,
  Trash2,
  Eye,
  Sparkles,
  Layers,
  ExternalLink,
  Copy,
  Check,
} from 'lucide-react'
import { Header } from '../components/Header'
import { Drawer } from '../components/Drawer'
import { Button } from '../components/Buttons'
import { Modal } from '../components/Modal'
import { useWorklogsPage } from '../hooks/useWorklogsPage'
import { useDocumentTitle } from '../hooks/useDocumentTitle'
import type {
  WorklogsPageProps,
  CreateWorklogFormData,
  UpdateWorklogFormData,
  WorklogWithUser,
} from '../types'

const CATEGORY_COLORS: Record<string, string> = {
  'Task Completion': 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
  Maintenance: 'bg-blue-500/15 text-blue-700 dark:text-blue-300 border-blue-500/30',
  Sanitation: 'bg-teal-500/15 text-teal-700 dark:text-teal-300 border-teal-500/30',
  Inspection: 'bg-amber-500/15 text-amber-700 dark:text-amber-300 border-amber-500/30',
  Academic: 'bg-indigo-500/15 text-indigo-700 dark:text-indigo-300 border-indigo-500/30',
  Administrative: 'bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/30',
  'Grievance Resolution': 'bg-rose-500/15 text-rose-700 dark:text-rose-300 border-rose-500/30',
  Operations: 'bg-cyan-500/15 text-cyan-700 dark:text-cyan-300 border-cyan-500/30',
  General: 'bg-gray/15 text-gray dark:text-gray/80 border-gray/30',
}

const SQL_MIGRATION_SNIPPET = `-- Run this in your Supabase SQL Editor:
CREATE TABLE IF NOT EXISTS public.worklogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE SET NULL,
  user_uid TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT DEFAULT 'General',
  hours_spent NUMERIC(5,2) DEFAULT 1.0,
  log_source TEXT DEFAULT 'Manual',
  completed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.worklogs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on worklogs" ON public.worklogs FOR ALL USING (true) WITH CHECK (true);

GRANT ALL ON TABLE public.worklogs TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;`

export const WorklogsPage = ({
  isDark,
  onToggleTheme,
  currentPath = '/worklogs',
  onNavigate,
}: WorklogsPageProps) => {
  useDocumentTitle('Worklogs & Activity | Grievance Portal')

  const {
    user,
    signOutUser,
    role,
    displayName,
    isAdminOrSuperAdmin,
    worklogs,
    filteredWorklogs,
    profiles,
    stats,
    categories,
    loading,
    refreshing,
    toast,
    dbNotice,
    searchQuery,
    setSearchQuery,
    categoryFilter,
    setCategoryFilter,
    sourceFilter,
    setSourceFilter,
    scopeFilter,
    setScopeFilter,
    dateFilter,
    setDateFilter,
    isAddModalOpen,
    setIsAddModalOpen,
    isEditModalOpen,
    setIsEditModalOpen,
    isDeleteModalOpen,
    setIsDeleteModalOpen,
    isDetailsModalOpen,
    setIsDetailsModalOpen,
    activeWorklog,
    actionLoading,
    modalError,
    handleOpenAdd,
    handleOpenEdit,
    handleOpenDelete,
    handleOpenDetails,
    fetchData,
    handleCreateWorklog,
    handleUpdateWorklog,
    handleDeleteWorklog,
  } = useWorklogsPage()

  const [isDrawerOpen, setIsDrawerOpen] = useState(false)
  const [copiedSql, setCopiedSql] = useState(false)

  // Add Modal Form State
  const [addForm, setAddForm] = useState<CreateWorklogFormData>({
    title: '',
    description: '',
    category: 'General',
    hours_spent: 1.0,
    completed_at: new Date().toISOString().split('T')[0],
    user_uid: '',
  })

  // Edit Modal Form State
  const [editForm, setEditForm] = useState<UpdateWorklogFormData>({
    id: 0,
    title: '',
    description: '',
    category: 'General',
    hours_spent: 1.0,
    completed_at: '',
  })

  // Open Add Modal Initializer
  const onOpenAddModal = () => {
    setAddForm({
      title: '',
      description: '',
      category: 'General',
      hours_spent: 1.0,
      completed_at: new Date().toISOString().split('T')[0],
      user_uid: user?.uid || '',
    })
    handleOpenAdd()
  }

  // Open Edit Modal Initializer
  const onOpenEditModal = (log: WorklogWithUser) => {
    setEditForm({
      id: log.id,
      title: log.title,
      description: log.description || '',
      category: log.category || 'General',
      hours_spent: Number(log.hours_spent) || 1.0,
      completed_at: (log.completed_at || log.created_at).split('T')[0],
    })
    handleOpenEdit(log)
  }

  const handleCopySql = () => {
    navigator.clipboard.writeText(SQL_MIGRATION_SNIPPET)
    setCopiedSql(true)
    setTimeout(() => setCopiedSql(false), 3000)
  }

  return (
    <div className="min-h-screen bg-offwhite dark:bg-[#151726] text-darkblue dark:text-offwhite transition-colors duration-200">
      {/* Navigation Drawer */}
      <Drawer
        isOpen={isDrawerOpen}
        onClose={() => setIsDrawerOpen(false)}
        currentPath={currentPath}
        onNavigate={onNavigate}
      />

      {/* Global Header */}
      <Header
        title="Work Activity Logs"
        subtitle="Completed Operational Works & Member Execution Log"
        isDark={isDark}
        onToggleTheme={onToggleTheme}
        onOpenDrawer={() => setIsDrawerOpen(true)}
        role={role}
        userEmail={user?.email}
        userName={displayName}
        onSignOut={() => signOutUser()}
      />

      {/* Toast Notification Banner */}
      {toast && (
        <div className="fixed top-20 right-4 sm:right-8 z-50 animate-bounce">
          <div
            className={`px-4 py-3 rounded-2xl shadow-xl flex items-center gap-3 text-sm font-semibold border ${
              toast.type === 'success'
                ? 'bg-emerald-500 text-white border-emerald-600'
                : toast.type === 'error'
                  ? 'bg-rose-500 text-white border-rose-600'
                  : 'bg-blue-600 text-white border-blue-700'
            }`}
          >
            {toast.type === 'success' ? (
              <CheckCircle2 className="w-4 h-4" />
            ) : (
              <AlertTriangle className="w-4 h-4" />
            )}
            <span>{toast.message}</span>
          </div>
        </div>
      )}

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-3 sm:px-6 lg:px-8 py-5 sm:py-8 space-y-6 sm:space-y-8">
        {/* Banner */}
        <div className="relative overflow-hidden rounded-2xl sm:rounded-3xl bg-gradient-to-br from-darkblue via-[#2a305e] to-lightblue p-5 sm:p-8 text-offwhite shadow-xl shadow-darkblue/10">
          <div className="relative z-10 max-w-2xl space-y-2">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/15 text-xs font-semibold backdrop-blur-xs">
              <Sparkles className="w-3.5 h-3.5 text-orange" />
              Operational Activity Archive
            </div>
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold tracking-tight">
              Worklogs & Completed Works
            </h2>
            <p className="text-xs sm:text-sm md:text-base text-offwhite/85">
              Comprehensive log of all executed assignments and manual work entries submitted across the council.
            </p>
          </div>

          <div className="hidden sm:block absolute right-0 bottom-0 opacity-10 pointer-events-none transform translate-x-8 translate-y-8">
            <FileText className="w-64 h-64 text-white" />
          </div>
        </div>

        {/* Database Table Notice Banner (If table is missing in Supabase) */}
        {dbNotice && (
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-4 sm:p-5 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div className="flex items-center gap-2.5 text-amber-800 dark:text-amber-200">
                <AlertTriangle className="w-5 h-5 shrink-0 text-amber-600" />
                <h4 className="text-sm font-bold">
                  Database Table Setup Notice
                </h4>
              </div>
              <button
                type="button"
                onClick={handleCopySql}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-amber-500 text-white text-xs font-semibold hover:bg-amber-600 transition-colors shadow-xs"
              >
                {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSql ? 'Copied SQL!' : 'Copy Setup SQL'}</span>
              </button>
            </div>
            <p className="text-xs text-amber-900/80 dark:text-amber-100/80 leading-relaxed">
              If the <code className="px-1.5 py-0.5 rounded bg-amber-500/20 font-mono text-[11px]">public.worklogs</code> table has not yet been created in Supabase, run the SQL script above in your Supabase SQL Editor.
            </p>
          </div>
        )}

        {/* Stats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-3.5 sm:gap-4">
          {stats.map((item) => {
            const Icon = item.icon
            return (
              <div
                key={item.title}
                className="bg-white dark:bg-[#20243a] p-4 sm:p-5 rounded-2xl border border-gray/15 dark:border-gray/10 shadow-xs hover:shadow-md transition-shadow space-y-3"
              >
                <div className="flex items-center justify-between">
                  <div
                    className={`w-9 h-9 rounded-xl bg-gradient-to-br ${item.color} flex items-center justify-center shadow-sm`}
                  >
                    <Icon className="w-4 h-4" />
                  </div>
                  <span className="text-xl sm:text-2xl font-black text-darkblue dark:text-offwhite">
                    {item.count}
                  </span>
                </div>
                <div>
                  <h3 className="text-xs font-bold text-darkblue dark:text-offwhite">
                    {item.title}
                  </h3>
                  <p className="text-[11px] text-gray mt-0.5">{item.change}</p>
                </div>
              </div>
            )
          })}
        </div>

        {/* Controls & Filter Bar */}
        <div className="bg-white dark:bg-[#1a1d2e] rounded-2xl border border-gray/15 dark:border-gray/10 p-4 space-y-4 shadow-xs">
          {/* Top Row: Scope Filter Tabs & Add Button */}
          <div className="flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3">
            {/* Scope Filter Tabs */}
            <div className="inline-flex p-1 rounded-xl bg-offwhite/70 dark:bg-[#151726]/70 border border-gray/15 self-start">
              <button
                type="button"
                onClick={() => setScopeFilter('all')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                  scopeFilter === 'all'
                    ? 'bg-darkblue text-offwhite dark:bg-orange dark:text-darkblue shadow-xs'
                    : 'text-gray hover:text-darkblue dark:hover:text-offwhite'
                }`}
              >
                All Worklogs ({worklogs.length})
              </button>
              <button
                type="button"
                onClick={() => setScopeFilter('my_logs')}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                  scopeFilter === 'my_logs'
                    ? 'bg-darkblue text-offwhite dark:bg-orange dark:text-darkblue shadow-xs'
                    : 'text-gray hover:text-darkblue dark:hover:text-offwhite'
                }`}
              >
                My Logs
              </button>
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-2 self-end md:self-auto">
              <Button
                variant="outline"
                size="sm"
                onClick={() => fetchData()}
                isLoading={refreshing}
                leftIcon={<RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />}
                className="text-xs font-medium"
              >
                Refresh
              </Button>

              <Button
                variant="primary"
                size="sm"
                onClick={onOpenAddModal}
                leftIcon={<Plus className="w-3.5 h-3.5" />}
                className="text-xs font-semibold shadow-sm"
              >
                Add Worklog
              </Button>
            </div>
          </div>

          {/* Bottom Row: Search, Category, Source, and Date Filters */}
          <div className="flex flex-col lg:flex-row items-stretch lg:items-center gap-3 pt-3 border-t border-gray/10">
            {/* Search Input */}
            <div className="relative flex-1">
              <Search className="w-4 h-4 text-gray absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search worklogs by title, description, member, category, or task..."
                className="w-full pl-9 pr-8 py-2 text-xs sm:text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite placeholder:text-gray focus:outline-none focus:ring-2 focus:ring-lightblue/30"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery('')}
                  className="absolute right-2.5 top-1/2 -translate-y-1/2 p-1 text-gray hover:text-darkblue dark:hover:text-offwhite"
                >
                  <X className="w-3.5 h-3.5" />
                </button>
              )}
            </div>

            {/* Filters row */}
            <div className="flex flex-wrap items-center gap-2.5">
              {/* Category Filter */}
              <div className="flex items-center gap-1.5">
                <span className="text-xs font-semibold text-gray shrink-0 hidden sm:inline">
                  Category:
                </span>
                <select
                  value={categoryFilter}
                  onChange={(e) => setCategoryFilter(e.target.value)}
                  className="px-2.5 py-2 rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-xs sm:text-sm font-semibold text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 cursor-pointer"
                >
                  {categories.map((c) => (
                    <option key={c} value={c}>
                      {c === 'All' ? 'All Categories' : c}
                    </option>
                  ))}
                </select>
              </div>

              {/* Source Filter */}
              <div className="flex items-center gap-1.5">
                <span className="text-xs font-semibold text-gray shrink-0 hidden sm:inline">
                  Source:
                </span>
                <select
                  value={sourceFilter}
                  onChange={(e) => setSourceFilter(e.target.value)}
                  className="px-2.5 py-2 rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-xs sm:text-sm font-semibold text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 cursor-pointer"
                >
                  <option value="All">All Sources</option>
                  <option value="Task Completion">Task Completion</option>
                  <option value="Manual">Manual Entry</option>
                </select>
              </div>

              {/* Date Filter */}
              <div className="flex items-center gap-1.5">
                <input
                  type="date"
                  value={dateFilter}
                  onChange={(e) => setDateFilter(e.target.value)}
                  className="px-2.5 py-1.5 rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-xs font-semibold text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
                  title="Filter by completion date"
                />
                {dateFilter && (
                  <button
                    type="button"
                    onClick={() => setDateFilter('')}
                    className="p-1.5 text-gray hover:text-darkblue dark:hover:text-offwhite text-xs"
                    title="Clear date"
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Worklogs Grid */}
        {loading ? (
          <div className="py-20 flex flex-col items-center justify-center space-y-3 bg-white dark:bg-[#1a1d2e] rounded-2xl border border-gray/15">
            <RefreshCw className="w-8 h-8 text-lightblue animate-spin" />
            <p className="text-sm font-medium text-gray">Loading worklogs...</p>
          </div>
        ) : filteredWorklogs.length === 0 ? (
          <div className="py-16 text-center bg-white dark:bg-[#1a1d2e] rounded-2xl border border-gray/15 space-y-3 p-6">
            <div className="w-12 h-12 rounded-full bg-lightblue/10 text-lightblue flex items-center justify-center mx-auto">
              <FileText className="w-6 h-6" />
            </div>
            <h3 className="text-base font-bold text-darkblue dark:text-offwhite">
              No Worklogs Found
            </h3>
            <p className="text-xs sm:text-sm text-gray max-w-md mx-auto">
              {searchQuery || categoryFilter !== 'All' || sourceFilter !== 'All' || dateFilter || scopeFilter !== 'all'
                ? 'No worklogs match your current search and filter settings. Try adjusting your filters.'
                : 'There are no recorded work activities yet. When members complete assigned works or add manual entries, they will appear here.'}
            </p>
            <Button variant="primary" size="sm" onClick={onOpenAddModal} className="mt-2">
              Add First Worklog
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-5">
            {filteredWorklogs.map((log) => {
              const isOwner = user?.uid === log.user_uid
              const canEdit = isOwner || isAdminOrSuperAdmin
              const categoryClass =
                CATEGORY_COLORS[log.category as keyof typeof CATEGORY_COLORS] || CATEGORY_COLORS.General

              const memberName =
                log.userProfile?.display_name || log.userProfile?.email || 'Council Member'
              const memberRole = log.userProfile?.role || 'Member'

              const logDate = new Date(log.completed_at || log.created_at).toLocaleDateString()

              return (
                <div
                  key={log.id}
                  className="bg-white dark:bg-[#1a1d2e] rounded-2xl border border-gray/15 dark:border-gray/10 p-5 shadow-xs hover:shadow-md transition-all flex flex-col justify-between space-y-4 group"
                >
                  {/* Top: Category, Source & Date */}
                  <div className="space-y-3">
                    <div className="flex items-center justify-between gap-2 flex-wrap">
                      <div className="flex items-center gap-1.5">
                        <span
                          className={`text-[10px] font-bold px-2 py-0.5 rounded-lg border ${categoryClass}`}
                        >
                          {log.category || 'General'}
                        </span>
                        <span
                          className={`text-[10px] font-semibold px-2 py-0.5 rounded-lg border ${
                            log.log_source === 'Task Completion'
                              ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 border-emerald-500/20'
                              : 'bg-purple-500/10 text-purple-700 dark:text-purple-300 border-purple-500/20'
                          }`}
                        >
                          {log.log_source}
                        </span>
                      </div>

                      <div className="flex items-center gap-2 text-[11px] text-gray font-medium">
                        <span className="inline-flex items-center gap-1">
                          <Calendar className="w-3 h-3 text-lightblue" />
                          {logDate}
                        </span>
                        <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-gray/10 font-bold text-darkblue dark:text-offwhite">
                          <Clock className="w-3 h-3 text-orange" />
                          {log.hours_spent}h
                        </span>
                      </div>
                    </div>

                    <h4 className="text-base font-bold text-darkblue dark:text-offwhite leading-snug group-hover:text-lightblue transition-colors line-clamp-2">
                      {log.title}
                    </h4>

                    {log.description && (
                      <p className="text-xs text-gray dark:text-gray/80 line-clamp-3 leading-relaxed">
                        {log.description}
                      </p>
                    )}
                  </div>

                  {/* Middle: Linked Task & Member Details */}
                  <div className="space-y-2.5 pt-3 border-t border-gray/10 text-xs">
                    {/* Linked Task Chip if from a task */}
                    {log.task && (
                      <div className="p-2 rounded-xl bg-lightblue/5 dark:bg-lightblue/10 border border-lightblue/20 flex items-center justify-between gap-2 text-[11px]">
                        <div className="flex items-center gap-1.5 min-w-0">
                          <Layers className="w-3.5 h-3.5 text-lightblue shrink-0" />
                          <span className="font-semibold text-darkblue dark:text-offwhite truncate">
                            Task: {log.task.title}
                          </span>
                        </div>
                        {onNavigate && (
                          <button
                            type="button"
                            onClick={() => onNavigate('/tasks')}
                            className="text-lightblue hover:underline shrink-0 flex items-center gap-0.5 text-[10px] font-bold"
                          >
                            View
                            <ExternalLink className="w-2.5 h-2.5" />
                          </button>
                        )}
                      </div>
                    )}

                    {/* Member Profile */}
                    <div className="flex items-center justify-between pt-1">
                      <div className="flex items-center gap-2 min-w-0">
                        <div className="w-7 h-7 rounded-full bg-lightblue/20 text-lightblue flex items-center justify-center text-xs font-bold uppercase shrink-0">
                          {memberName.charAt(0)}
                        </div>
                        <div className="min-w-0">
                          <p className="font-semibold text-darkblue dark:text-offwhite truncate text-xs">
                            {memberName} {isOwner && <span className="text-lightblue">(You)</span>}
                          </p>
                          <p className="text-[10px] text-gray capitalize truncate">
                            {memberRole}
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Bottom: Action Buttons */}
                  <div className="pt-2 flex items-center justify-between gap-1.5 border-t border-gray/10">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleOpenDetails(log)}
                      leftIcon={<Eye className="w-3.5 h-3.5" />}
                      className="text-xs px-2.5 font-medium"
                    >
                      Details
                    </Button>

                    <div className="flex items-center gap-1">
                      {canEdit && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => onOpenEditModal(log)}
                          className="p-1.5 text-gray hover:text-darkblue dark:hover:text-offwhite"
                          title="Edit worklog"
                        >
                          <Edit3 className="w-3.5 h-3.5" />
                        </Button>
                      )}

                      {canEdit && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleOpenDelete(log)}
                          className="p-1.5 text-rose-500 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/30"
                          title="Delete worklog"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        )}
      </main>

      {/* ========================================================= */}
      {/* 1. ADD WORKLOG MODAL                                      */}
      {/* ========================================================= */}
      <Modal
        isOpen={isAddModalOpen}
        onClose={() => !actionLoading && setIsAddModalOpen(false)}
        title="Add Manual Worklog"
        size="lg"
      >
        <form
          onSubmit={(e) => {
            e.preventDefault()
            handleCreateWorklog(addForm)
          }}
          className="space-y-4"
        >
          {modalError && (
            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs font-semibold text-rose-600 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <span>{modalError}</span>
            </div>
          )}

          {/* Title */}
          <div>
            <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
              Work Title <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              value={addForm.title}
              onChange={(e) => setAddForm({ ...addForm, title: e.target.value })}
              placeholder="e.g., Repaired water dispenser in Library 2nd floor"
              className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
              Work Details / Notes
            </label>
            <textarea
              rows={3}
              value={addForm.description}
              onChange={(e) => setAddForm({ ...addForm, description: e.target.value })}
              placeholder="Describe the action taken, resources used, or final outcome..."
              className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 resize-none"
            />
          </div>

          {/* Category, Hours & Date */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Category
              </label>
              <select
                value={addForm.category}
                onChange={(e) => setAddForm({ ...addForm, category: e.target.value })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 cursor-pointer"
              >
                <option value="General">General</option>
                <option value="Maintenance">Maintenance</option>
                <option value="Sanitation">Sanitation</option>
                <option value="Inspection">Inspection</option>
                <option value="Academic">Academic</option>
                <option value="Administrative">Administrative</option>
                <option value="Grievance Resolution">Grievance Resolution</option>
                <option value="Operations">Operations</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Hours Spent
              </label>
              <input
                type="number"
                step="0.25"
                min="0.25"
                max="100"
                value={addForm.hours_spent}
                onChange={(e) => setAddForm({ ...addForm, hours_spent: Number(e.target.value) })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Completed Date
              </label>
              <input
                type="date"
                value={addForm.completed_at}
                onChange={(e) => setAddForm({ ...addForm, completed_at: e.target.value })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
              />
            </div>
          </div>

          {/* Member Attribution Selector (If admin logging for someone else) */}
          {isAdminOrSuperAdmin && (
            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Log for Member (Defaults to You)
              </label>
              <select
                value={addForm.user_uid}
                onChange={(e) => setAddForm({ ...addForm, user_uid: e.target.value })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 cursor-pointer"
              >
                <option value="">Myself ({displayName || user?.email})</option>
                {profiles.map((p) => (
                  <option key={p.firebase_uid} value={p.firebase_uid}>
                    {p.display_name || p.email} ({p.role})
                  </option>
                ))}
              </select>
            </div>
          )}

          <div className="pt-3 flex items-center justify-end gap-2 border-t border-gray/10">
            <Button
              variant="outline"
              type="button"
              onClick={() => setIsAddModalOpen(false)}
              disabled={actionLoading}
            >
              Cancel
            </Button>
            <Button variant="primary" type="submit" isLoading={actionLoading}>
              Save Worklog
            </Button>
          </div>
        </form>
      </Modal>

      {/* ========================================================= */}
      {/* 2. EDIT WORKLOG MODAL                                     */}
      {/* ========================================================= */}
      <Modal
        isOpen={isEditModalOpen}
        onClose={() => !actionLoading && setIsEditModalOpen(false)}
        title="Edit Worklog"
        size="lg"
      >
        <form
          onSubmit={(e) => {
            e.preventDefault()
            handleUpdateWorklog(editForm)
          }}
          className="space-y-4"
        >
          {modalError && (
            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs font-semibold text-rose-600 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0" />
              <span>{modalError}</span>
            </div>
          )}

          <div>
            <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
              Work Title <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              value={editForm.title}
              onChange={(e) => setEditForm({ ...editForm, title: e.target.value })}
              className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
              Work Details / Notes
            </label>
            <textarea
              rows={3}
              value={editForm.description}
              onChange={(e) => setEditForm({ ...editForm, description: e.target.value })}
              className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 resize-none"
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Category
              </label>
              <select
                value={editForm.category}
                onChange={(e) => setEditForm({ ...editForm, category: e.target.value })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30 cursor-pointer"
              >
                <option value="General">General</option>
                <option value="Maintenance">Maintenance</option>
                <option value="Sanitation">Sanitation</option>
                <option value="Inspection">Inspection</option>
                <option value="Academic">Academic</option>
                <option value="Administrative">Administrative</option>
                <option value="Grievance Resolution">Grievance Resolution</option>
                <option value="Operations">Operations</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Hours Spent
              </label>
              <input
                type="number"
                step="0.25"
                min="0.25"
                max="100"
                value={editForm.hours_spent}
                onChange={(e) => setEditForm({ ...editForm, hours_spent: Number(e.target.value) })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-darkblue dark:text-offwhite mb-1.5">
                Completed Date
              </label>
              <input
                type="date"
                value={editForm.completed_at}
                onChange={(e) => setEditForm({ ...editForm, completed_at: e.target.value })}
                className="w-full px-3 py-2 text-sm rounded-xl border border-gray/20 dark:border-gray/15 bg-offwhite/50 dark:bg-[#151726]/60 text-darkblue dark:text-offwhite focus:outline-none focus:ring-2 focus:ring-lightblue/30"
              />
            </div>
          </div>

          <div className="pt-3 flex items-center justify-end gap-2 border-t border-gray/10">
            <Button
              variant="outline"
              type="button"
              onClick={() => setIsEditModalOpen(false)}
              disabled={actionLoading}
            >
              Cancel
            </Button>
            <Button variant="primary" type="submit" isLoading={actionLoading}>
              Save Changes
            </Button>
          </div>
        </form>
      </Modal>

      {/* ========================================================= */}
      {/* 3. WORKLOG DETAILS MODAL                                  */}
      {/* ========================================================= */}
      {activeWorklog && (
        <Modal
          isOpen={isDetailsModalOpen}
          onClose={() => setIsDetailsModalOpen(false)}
          title="Worklog Details"
          size="md"
        >
          <div className="space-y-4">
            <div className="flex items-center gap-2 flex-wrap pb-2 border-b border-gray/10">
              <span
                className={`text-xs font-bold px-2.5 py-0.5 rounded-lg border ${
                  CATEGORY_COLORS[activeWorklog.category as keyof typeof CATEGORY_COLORS] ||
                  CATEGORY_COLORS.General
                }`}
              >
                {activeWorklog.category}
              </span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded-md bg-gray/10">
                Source: {activeWorklog.log_source}
              </span>
              <span className="text-xs font-semibold px-2 py-0.5 rounded-md bg-orange/15 text-orange">
                {activeWorklog.hours_spent} hours
              </span>
            </div>

            <div className="space-y-1">
              <h3 className="text-base font-bold text-darkblue dark:text-offwhite">
                {activeWorklog.title}
              </h3>
              {activeWorklog.description && (
                <p className="text-xs sm:text-sm text-gray dark:text-gray/80 leading-relaxed bg-offwhite/50 dark:bg-[#151726]/40 p-3 rounded-xl border border-gray/10">
                  {activeWorklog.description}
                </p>
              )}
            </div>

            {/* Author info */}
            <div className="p-3 rounded-xl bg-offwhite/40 dark:bg-[#151726]/30 border border-gray/10 text-xs space-y-1">
              <p className="text-gray text-[11px] font-semibold uppercase tracking-wide">
                Recorded by
              </p>
              <p className="font-bold text-darkblue dark:text-offwhite">
                {activeWorklog.userProfile?.display_name ||
                  activeWorklog.userProfile?.email ||
                  activeWorklog.user_uid}
              </p>
              <p className="text-gray">
                Role: <span className="capitalize">{activeWorklog.userProfile?.role || 'Member'}</span> • Email: {activeWorklog.userProfile?.email || 'N/A'}
              </p>
            </div>

            {/* Linked task */}
            {activeWorklog.task && (
              <div className="p-3 rounded-xl bg-lightblue/10 border border-lightblue/20 text-xs space-y-1">
                <p className="text-lightblue font-semibold uppercase tracking-wide text-[11px]">
                  Associated Task Assignment
                </p>
                <p className="font-bold text-darkblue dark:text-offwhite">
                  {activeWorklog.task.title}
                </p>
                {activeWorklog.task.description && (
                  <p className="text-gray text-[11px] line-clamp-2">
                    {activeWorklog.task.description}
                  </p>
                )}
              </div>
            )}

            <div className="text-[11px] text-gray flex items-center justify-between pt-2 border-t border-gray/10">
              <span>
                Completed:{' '}
                {new Date(activeWorklog.completed_at || activeWorklog.created_at).toLocaleString()}
              </span>
            </div>

            <div className="pt-3 flex justify-end border-t border-gray/10">
              <Button variant="outline" onClick={() => setIsDetailsModalOpen(false)}>
                Close
              </Button>
            </div>
          </div>
        </Modal>
      )}

      {/* ========================================================= */}
      {/* 4. DELETE CONFIRMATION MODAL                              */}
      {/* ========================================================= */}
      {activeWorklog && (
        <Modal
          isOpen={isDeleteModalOpen}
          onClose={() => !actionLoading && setIsDeleteModalOpen(false)}
          title="Delete Worklog"
          size="md"
        >
          <div className="space-y-4">
            {modalError && (
              <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs font-semibold text-rose-600 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 shrink-0" />
                <span>{modalError}</span>
              </div>
            )}

            <p className="text-xs sm:text-sm text-gray">
              Are you sure you want to delete this worklog entry?
            </p>

            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs text-rose-700 dark:text-rose-300 space-y-1">
              <p className="font-bold">{activeWorklog.title}</p>
              <p>This action cannot be undone.</p>
            </div>

            <div className="pt-3 flex items-center justify-end gap-2 border-t border-gray/10">
              <Button
                variant="outline"
                onClick={() => setIsDeleteModalOpen(false)}
                disabled={actionLoading}
              >
                Cancel
              </Button>
              <Button
                variant="primary"
                onClick={handleDeleteWorklog}
                isLoading={actionLoading}
                leftIcon={<Trash2 className="w-3.5 h-3.5" />}
                className="bg-rose-600 hover:bg-rose-700 text-white focus:ring-rose-500/30"
              >
                Confirm Delete
              </Button>
            </div>
          </div>
        </Modal>
      )}
    </div>
  )
}

export default WorklogsPage
